# Generated by Django 6.0.6 on 2026-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
